CREATE_SUBDIR_PER_RUN: True
server_file: ./server.py
client_file: ./client.py
config: ./config.yaml
data_dir: ../datasets/flamingo_generated/
work_dir: ./runs/cifar10/
seed: 2024
batch_size: 64
test_batch_size: 64
lr: 0.001
weight_decay: 0.0001
max_epochs: 100
dropout: 0.5
momentum: 0.9
local_epochs: 1
num_clients: 30
num_training_clients: 15
alpha: 0.01
beta: 0.01
steps: 2
optim_steps: 15
method: fedmeta
model_type: cnn
dataset_type: cifar10
log_path: ./runs/cifar10/2023-12-30-18-00-33/logs.log
verb: 1
run_dir: ./runs/cifar10/2023-12-30-18-00-33
saved_config_dir: ./runs/cifar10/2023-12-30-18-00-33/config.yaml
